import { createHash } from "node:crypto";
import type { ProposalSigningSessionRecord } from "./contracts";
import {
  getProposalSigningReceiptRecovery,
  getProposalSigningServiceClient,
  getProposalSigningSession,
  registerProposalSigningReceipt,
  type ProposalSigningReceiptRecoveryKeys,
} from "./db";
import {
  buildProposalSigningReceiptPdf,
  getProposalSigningReceiptFileName,
} from "./pdf";

const RECEIPT_BUCKET = "customer-documents";

export type EnsureProposalSigningReceiptResult =
  | { ok: true; session: ProposalSigningSessionRecord }
  | { ok: false; message: string };

type RefreshProposalSigningReceiptState = () => ReturnType<
  typeof getProposalSigningSession
>;

function receiptStoragePath(session: ProposalSigningSessionRecord) {
  const acceptanceId = session.acceptance?.acceptanceId;
  if (!acceptanceId) {
    throw new Error("Signed acceptance evidence is unavailable.");
  }

  return `${session.proposal.companyId}/proposal-signing/${session.requestId}/${acceptanceId}.pdf`;
}

async function exactObjectAlreadyExists({
  bucket,
  path,
  sha256,
}: {
  bucket: string;
  path: string;
  sha256: string;
}) {
  const client = getProposalSigningServiceClient();
  if (!client) return false;
  const { data, error } = await client.storage.from(bucket).download(path);
  if (error || !data) return false;
  const existing = Buffer.from(await data.arrayBuffer());
  return createHash("sha256").update(existing).digest("hex") === sha256;
}

async function removeExactUnregisteredReceiptObject({
  bucket,
  path,
  sha256,
}: {
  bucket: string;
  path: string;
  sha256: string;
}) {
  const client = getProposalSigningServiceClient();
  if (!client) return false;

  // Never issue a removal based on path alone. The current private bytes must
  // still be the exact deterministic receipt generated by this acceptance.
  if (!(await exactObjectAlreadyExists({ bucket, path, sha256 }))) {
    return false;
  }

  const { data: removed, error: removeError } = await client.storage
    .from(bucket)
    .remove([path]);
  if (
    removeError ||
    !Array.isArray(removed) ||
    removed.length !== 1 ||
    removed[0]?.name !== path
  ) {
    return false;
  }

  const existence = await client.storage.from(bucket).exists(path);
  const missingStatus = Number(
    (existence.error as { status?: number | string } | null)?.status,
  );
  return (
    existence.data === false &&
    existence.error !== null &&
    (missingStatus === 400 || missingStatus === 404)
  );
}

async function ensureProposalSigningReceiptWithRefresh(
  session: ProposalSigningSessionRecord,
  refresh: RefreshProposalSigningReceiptState,
): Promise<EnsureProposalSigningReceiptResult> {
  if (session.status !== "signed" || !session.acceptance) {
    return { ok: false, message: "The proposal has not been electronically signed." };
  }

  if (session.receipt) {
    return { ok: true, session };
  }

  const client = getProposalSigningServiceClient();
  if (!client) {
    return { ok: false, message: "The secure receipt service is not configured." };
  }

  const content = buildProposalSigningReceiptPdf({
    session,
    acceptance: session.acceptance,
  });
  const sha256 = createHash("sha256").update(content).digest("hex");
  const fileName = getProposalSigningReceiptFileName(session);
  const storagePath = receiptStoragePath(session);
  const { error: uploadError } = await client.storage
    .from(RECEIPT_BUCKET)
    .upload(storagePath, content, {
      cacheControl: "0",
      contentType: "application/pdf",
      upsert: false,
    });

  if (
    uploadError &&
    !(await exactObjectAlreadyExists({
      bucket: RECEIPT_BUCKET,
      path: storagePath,
      sha256,
    }))
  ) {
    return { ok: false, message: "The signed receipt could not be stored securely." };
  }

  const registration = await registerProposalSigningReceipt({
    operationKey: session.acceptance.acceptanceId,
    companyId: session.proposal.companyId,
    requestId: session.requestId,
    acceptanceId: session.acceptance.acceptanceId,
    documentId: session.acceptance.acceptanceId,
    fileName,
    fileSizeBytes: content.byteLength,
    mimeType: "application/pdf",
    storageBucket: RECEIPT_BUCKET,
    storagePath,
    signedDocumentSha256: sha256,
  });
  const refreshed = await refresh();

  if (refreshed.ok && refreshed.receipt?.sha256 === sha256) {
    return { ok: true, session: refreshed };
  }

  if (registration.ok === false && registration.status !== "unavailable") {
    // A typed ok:false envelope proves the registration transaction did not
    // commit. Re-read immediately so a concurrent/idempotent registration wins
    // over cleanup. Only an exact, still-unregistered digest may be removed.
    const conclusiveRead = await refresh();
    if (conclusiveRead.ok && conclusiveRead.receipt?.sha256 === sha256) {
      return { ok: true, session: conclusiveRead };
    }
    if (!conclusiveRead.ok || conclusiveRead.receipt) {
      return {
        ok: false,
        message: "The signature is recorded, but its receipt state could not be reconciled safely.",
      };
    }

    const removed = await removeExactUnregisteredReceiptObject({
      bucket: RECEIPT_BUCKET,
      path: storagePath,
      sha256,
    });
    return {
      ok: false,
      message: removed
        ? "The signature is recorded, but its receipt could not be registered. No unregistered file was retained."
        : "The signature is recorded, but its unregistered receipt could not be cleaned up safely.",
    };
  }

  // A transport failure can occur after the database commits. Keep this one
  // deterministic, digest-verified object for the next idempotent reconciliation
  // instead of risking removal of a receipt that was successfully registered.
  return { ok: false, message: "The signature is recorded, but its receipt is not ready yet." };
}

export function ensureProposalSigningReceipt(
  session: ProposalSigningSessionRecord,
  sessionHash: string,
): Promise<EnsureProposalSigningReceiptResult> {
  return ensureProposalSigningReceiptWithRefresh(session, () =>
    getProposalSigningSession({
      requestId: session.requestId,
      sessionHash,
    }),
  );
}

export function ensureProposalSigningReceiptFromRecovery(
  session: ProposalSigningSessionRecord,
  recoveryKeys: ProposalSigningReceiptRecoveryKeys,
): Promise<EnsureProposalSigningReceiptResult> {
  if (
    session.requestId !== recoveryKeys.requestId ||
    session.proposal.companyId !== recoveryKeys.companyId ||
    session.acceptance?.acceptanceId !== recoveryKeys.acceptanceId
  ) {
    return Promise.resolve({
      ok: false,
      message: "The signed proposal does not match the requested receipt recovery scope.",
    });
  }

  return ensureProposalSigningReceiptWithRefresh(session, () =>
    getProposalSigningReceiptRecovery(recoveryKeys),
  );
}
