export const REGRESSION_SIDE_EFFECT_FLAGS = [
  'AI_ACTION_EXECUTION_ENABLED',
  'AI_ENABLED',
  'DOCUSIGN_PROVIDER_WRITES_ENABLED',
  'DOCUSIGN_SIGNATURE_REQUESTS_ENABLED',
  'DROPBOX_SIGN_PROVIDER_WRITES_ENABLED',
  'DROPBOX_SIGN_SIGNATURE_REQUESTS_ENABLED',
  'GHL_SYNC_ENABLED',
  'GOOGLE_BUSINESS_PROFILE_REVIEW_REPLY_ENABLED',
  'GOOGLE_BUSINESS_PROFILE_SYNC_ENABLED',
  'GOOGLE_CALENDAR_WRITE_ENABLED',
  'GOOGLE_GMAIL_SEND_ENABLED',
  'IHC_WEBSITE_INTAKE_ENABLED',
  'QUICKBOOKS_ACCOUNTING_WRITES_ENABLED',
  'QUICKBOOKS_PAYMENT_PROCESSING_ENABLED',
  'QUICKBOOKS_SYNC_ENABLED',
  'STRIPE_LIVE_PAYMENTS_ENABLED',
  'STRIPE_REFUNDS_ENABLED',
  'STRIPE_WEBHOOK_PROCESSING_ENABLED',
  'TWILIO_INBOUND_SMS_ENABLED',
  'TWILIO_OUTBOUND_SMS_ENABLED',
  'TWILIO_WEATHERTECH_TUCSON_VOICE_FORWARDING_ENABLED',
  'WEATHERTECH_TUCSON_WEBSITE_INTAKE_ENABLED',
  'WEATHERTECH_WEBSITE_INTAKE_ENABLED',
  'WEBSITE_INTAKE_ENABLED',
  'WTOS_AUTOMATED_CUSTOMER_NOTIFICATIONS_ENABLED',
  'WTOS_CUSTOMER_PORTAL_ENABLED',
  'WTOS_PRODUCTION_APPROVED',
  'WTOS_PUBLIC_REGISTRATION_ENABLED',
  'YELP_LIVE_SYNC_ENABLED',
  'YELP_LIVE_SYNC_ENABLED_IHC',
  'YELP_LIVE_SYNC_ENABLED_WEATHERTECH_PHOENIX',
  'YELP_LIVE_SYNC_ENABLED_WEATHERTECH_TUCSON',
  'YELP_OUTBOUND_MESSAGING_ENABLED',
  'YELP_OUTBOUND_MESSAGING_ENABLED_IHC',
  'YELP_OUTBOUND_MESSAGING_ENABLED_WEATHERTECH_PHOENIX',
  'YELP_OUTBOUND_MESSAGING_ENABLED_WEATHERTECH_TUCSON',
] as const;

export function getRegressionSideEffectSafety(
  env: Record<string, string | undefined> = process.env,
) {
  const hasEnabledSideEffect = REGRESSION_SIDE_EFFECT_FLAGS.some(
    (name) => env[name]?.trim().toLowerCase() === 'true',
  );

  return hasEnabledSideEffect ? 'enabled' : 'disabled';
}
