import type { CrmSnapshot } from "./types";

function isoDate(daysFromToday = 0) {
  const date = new Date();
  date.setDate(date.getDate() + daysFromToday);
  return date.toISOString().slice(0, 10);
}

function isoDateTime(daysFromToday = 0, hour = 9) {
  const date = new Date();
  date.setDate(date.getDate() + daysFromToday);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

export function isCrmDemoFallbackEnabled() {
  return process.env.NEXT_PUBLIC_DISABLE_CRM_DEMO_FALLBACK !== "true";
}

export function createDemoCrmSnapshot(): CrmSnapshot {
  const now = new Date().toISOString();

  const weatherTechCompanyId = "demo-company-weathertech";
  const ihcCompanyId = "demo-company-ihc";
  const weatherTechCustomerId = "demo-customer-weathertech-1";
  const ihcCustomerId = "demo-customer-ihc-1";
  const weatherTechLeadId = "demo-lead-weathertech-1";
  const ihcLeadId = "demo-lead-ihc-1";
  const weatherTechEstimateId = "demo-estimate-weathertech-1";
  const ihcEstimateId = "demo-estimate-ihc-1";
  const weatherTechJobId = "demo-job-weathertech-1";
  const ihcJobId = "demo-job-ihc-1";
  const weatherTechInvoiceId = "demo-invoice-weathertech-1";
  const employeeId = "demo-employee-1";

  return {
    companies: [
      {
        id: weatherTechCompanyId,
        name: "WeatherTech Roofing LLC",
        trade: "roofing",
        short_name: "WeatherTech",
        brand_color: "#0ea5e9",
        workflow_profile: "roofing",
        phone: "(480) 848-3486",
        email: "weathertechroofingaz@gmail.com",
        created_at: now,
        updated_at: now,
      },
      {
        id: ihcCompanyId,
        name: "IHC Painting",
        trade: "painting",
        short_name: "IHC",
        brand_color: "#f97316",
        workflow_profile: "painting",
        phone: "(480) 848-3486",
        email: "weathertechroofingaz@gmail.com",
        created_at: now,
        updated_at: now,
      },
    ],
    customers: [
      {
        id: weatherTechCustomerId,
        company_id: weatherTechCompanyId,
        display_name: "Demo Roof Customer",
        contact_name: "Demo Roof Customer",
        phone: "(480) 555-0101",
        email: "roof-demo@example.com",
        property_address: "1234 E Demo Roof Rd",
        city: "Gilbert",
        state: "AZ",
        postal_code: "85234",
        customer_type: "homeowner",
        status: "active",
        notes: "Local demo customer so WeatherTech OS can run without live Supabase.",
        created_at: now,
        updated_at: now,
      },
      {
        id: ihcCustomerId,
        company_id: ihcCompanyId,
        display_name: "Demo Paint Customer",
        contact_name: "Demo Paint Customer",
        phone: "(480) 555-0102",
        email: "paint-demo@example.com",
        property_address: "4567 S Demo Paint Ave",
        city: "Chandler",
        state: "AZ",
        postal_code: "85286",
        customer_type: "homeowner",
        status: "active",
        notes: "Local demo customer for IHC Painting.",
        created_at: now,
        updated_at: now,
      },
    ],
    leads: [
      {
        id: weatherTechLeadId,
        company_id: weatherTechCompanyId,
        customer_id: null,
        contact_name: "New Roof Lead",
        phone: "(480) 555-0199",
        email: "new-roof-lead@example.com",
        property_address: "7890 W Monsoon Dr",
        city: "Mesa",
        state: "AZ",
        postal_code: "85201",
        latitude: null,
        longitude: null,
        google_place_id: null,
        address_verified_at: null,
        service_type: "roofing",
        source: "Website",
        status: "qualified",
        pipeline_stage: "estimate_scheduled",
        priority: "high",
        estimated_value: 18500,
        next_follow_up: isoDate(1),
        notes: "Demo roofing lead.",
        created_by: null,
        created_at: now,
        updated_at: now,
      },
      {
        id: ihcLeadId,
        company_id: ihcCompanyId,
        customer_id: null,
        contact_name: "Exterior Paint Lead",
        phone: "(480) 555-0188",
        email: "paint-lead@example.com",
        property_address: "2345 N Color Way",
        city: "Scottsdale",
        state: "AZ",
        postal_code: "85251",
        latitude: null,
        longitude: null,
        google_place_id: null,
        address_verified_at: null,
        service_type: "painting",
        source: "Referral",
        status: "new",
        pipeline_stage: "new_lead",
        priority: "normal",
        estimated_value: 9200,
        next_follow_up: isoDate(2),
        notes: "Demo painting lead.",
        created_by: null,
        created_at: now,
        updated_at: now,
      },
    ],
    estimates: [
      {
        id: weatherTechEstimateId,
        company_id: weatherTechCompanyId,
        customer_id: weatherTechCustomerId,
        lead_id: weatherTechLeadId,
        business: "WeatherTech Roofing LLC",
        location: "1234 E Demo Roof Rd",
        title: "Demo Tile Underlayment Estimate",
        status: "sent",
        service_type: "roofing",
        issue_date: isoDate(0),
        expiration_date: isoDate(14),
        subtotal: 18000,
        labor_total: 9000,
        material_total: 9000,
        tax_rate: 0.08,
        tax_total: 720,
        discount_type: "fixed",
        discount_value: 0,
        discount_total: 0,
        profit_margin_rate: 0.28,
        profit_margin_total: 5040,
        total: 18720,
        notes: "Demo estimate.",
        scope_of_work:
          "Demo roofing scope covering underlayment replacement, material staging, installation, cleanup, and final walkthrough.",
        painting_area_type: null,
        paint_brand: "N/A",
        paint_product_line: null,
        paint_finish: null,
        color_selection_status: "not_started",
        paint_color_body: null,
        paint_color_trim: null,
        paint_color_accent: null,
        surface_prep_level: null,
        coats: 0,
        primer_required: false,
        created_at: now,
        updated_at: now,
      },
      {
        id: ihcEstimateId,
        company_id: ihcCompanyId,
        customer_id: ihcCustomerId,
        lead_id: ihcLeadId,
        business: "IHC Painting",
        location: "4567 S Demo Paint Ave",
        title: "Demo Exterior Repaint Estimate",
        status: "draft",
        service_type: "painting",
        issue_date: isoDate(0),
        expiration_date: isoDate(14),
        subtotal: 9200,
        labor_total: 5200,
        material_total: 4000,
        tax_rate: 0.08,
        tax_total: 320,
        discount_type: "fixed",
        discount_value: 0,
        discount_total: 0,
        profit_margin_rate: 0.32,
        profit_margin_total: 2944,
        total: 9520,
        notes: "Demo painting estimate.",
        scope_of_work:
          "Demo exterior painting scope covering prep, masking, Dunn-Edwards coating application, cleanup, and color walkthrough.",
        painting_area_type: "exterior",
        paint_brand: "Dunn-Edwards",
        paint_product_line: "Evershield",
        paint_finish: "satin",
        color_selection_status: "in_review",
        paint_color_body: "Warm White",
        paint_color_trim: "Swiss Coffee",
        paint_color_accent: "Iron Ore",
        surface_prep_level: "standard",
        coats: 2,
        primer_required: true,
        created_at: now,
        updated_at: now,
      },
    ],
    estimateLineItems: [
      {
        id: "demo-estimate-line-1",
        estimate_id: weatherTechEstimateId,
        category: "labor",
        name: "Roofing labor",
        description: "Demo labor line",
        quantity: 1,
        unit: "project",
        unit_cost: 9000,
        unit_price: 9000,
        markup_rate: 0,
        taxable: false,
        sort_order: 1,
        total: 9000,
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-estimate-line-2",
        estimate_id: weatherTechEstimateId,
        category: "material",
        name: "Roofing materials",
        description: "Demo materials line",
        quantity: 1,
        unit: "project",
        unit_cost: 9000,
        unit_price: 9000,
        markup_rate: 0,
        taxable: true,
        sort_order: 2,
        total: 9000,
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-estimate-line-3",
        estimate_id: ihcEstimateId,
        category: "labor",
        name: "Painting labor",
        description: "Demo paint labor",
        quantity: 1,
        unit: "project",
        unit_cost: 5200,
        unit_price: 5200,
        markup_rate: 0,
        taxable: false,
        sort_order: 1,
        total: 5200,
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-estimate-line-4",
        estimate_id: ihcEstimateId,
        category: "material",
        name: "Paint and sundries",
        description: "Demo paint materials",
        quantity: 1,
        unit: "project",
        unit_cost: 4000,
        unit_price: 4000,
        markup_rate: 0,
        taxable: true,
        sort_order: 2,
        total: 4000,
        created_at: now,
        updated_at: now,
      },
    ],
    scopeTemplates: [],
    scopes: [
      {
        id: "demo-scope-1",
        company_id: weatherTechCompanyId,
        customer_id: weatherTechCustomerId,
        lead_id: weatherTechLeadId,
        estimate_id: weatherTechEstimateId,
        template_id: null,
        title: "Demo Roofing Scope",
        category: "tile_underlayment",
        status: "ready",
        scope_body: "Remove existing tile, replace underlayment, reinstall tile, clean jobsite.",
        notes: "Demo scope.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-scope-2",
        company_id: ihcCompanyId,
        customer_id: ihcCustomerId,
        lead_id: ihcLeadId,
        estimate_id: ihcEstimateId,
        template_id: null,
        title: "Demo Painting Scope",
        category: "exterior_painting",
        status: "draft",
        scope_body: "Pressure wash, prep surfaces, prime as needed, apply two finish coats.",
        notes: "Demo painting scope.",
        created_at: now,
        updated_at: now,
      },
    ],
    jobs: [
      {
        id: weatherTechJobId,
        company_id: weatherTechCompanyId,
        customer_id: weatherTechCustomerId,
        lead_id: weatherTechLeadId,
        estimate_id: weatherTechEstimateId,
        scope_id: "demo-scope-1",
        business: "WeatherTech Roofing",
        location: "1234 E Demo Roof Rd, Gilbert, AZ",
        title: "Demo Roof Production Job",
        service_type: "roofing",
        status: "scheduled",
        scheduled_start: `${isoDate(3)}T08:00:00.000Z`,
        scheduled_end: `${isoDate(6)}T17:00:00.000Z`,
        start_date: isoDate(3),
        end_date: isoDate(6),
        crew_name: "Roof Crew A",
        project_manager: "Joe",
        address: "1234 E Demo Roof Rd, Gilbert, AZ",
        property_address: "1234 E Demo Roof Rd, Gilbert, AZ",
        scope_of_work: "Remove existing tile, replace underlayment, reinstall tile, clean jobsite.",
        total: 18450,
        latitude: null,
        longitude: null,
        google_place_id: null,
        address_verified_at: null,
        notes: "Demo production job.",
        created_at: now,
        updated_at: now,
      },
      {
        id: ihcJobId,
        company_id: ihcCompanyId,
        customer_id: ihcCustomerId,
        lead_id: ihcLeadId,
        estimate_id: ihcEstimateId,
        scope_id: "demo-scope-2",
        business: "IHC Painting",
        location: "4567 S Demo Paint Ave, Chandler, AZ",
        title: "Demo Exterior Paint Job",
        service_type: "painting",
        status: "in_progress",
        scheduled_start: `${isoDate(1)}T08:00:00.000Z`,
        scheduled_end: `${isoDate(4)}T17:00:00.000Z`,
        start_date: isoDate(1),
        end_date: isoDate(4),
        crew_name: "Paint Crew 1",
        project_manager: "Joe",
        address: "4567 S Demo Paint Ave, Chandler, AZ",
        property_address: "4567 S Demo Paint Ave, Chandler, AZ",
        scope_of_work: "Pressure wash, prep surfaces, prime as needed, apply two finish coats.",
        total: 9200,
        latitude: null,
        longitude: null,
        google_place_id: null,
        address_verified_at: null,
        notes: "Demo IHC production job.",
        created_at: now,
        updated_at: now,
      },
    ],
    jobTasks: [
      {
        id: "demo-task-weathertech-staging",
        job_id: weatherTechJobId,
        title: "Confirm underlayment and flashing staging",
        description: "Verify WeatherTech roofing materials are ready before dry-in.",
        status: "todo",
        sort_order: 0,
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-task-weathertech-protection",
        job_id: weatherTechJobId,
        title: "Protect landscaping and access points",
        description: null,
        status: "in_progress",
        sort_order: 1,
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-task-ihc-colors",
        job_id: ihcJobId,
        title: "Confirm Dunn-Edwards colors and sheen",
        description: "Keep IHC color approvals separate from roofing production defaults.",
        status: "done",
        sort_order: 0,
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-task-ihc-masking",
        job_id: ihcJobId,
        title: "Complete prep and masking review",
        description: null,
        status: "in_progress",
        sort_order: 1,
        created_at: now,
        updated_at: now,
      },
    ],
    jobNotes: [
      {
        id: "demo-note-weathertech",
        job_id: weatherTechJobId,
        note: "Customer requested driveway access remain clear during material staging.",
        created_at: now,
      },
      {
        id: "demo-note-ihc",
        job_id: ihcJobId,
        note: "IHC crew confirmed exterior access window and color review.",
        created_at: now,
      },
    ],
    jobMaterials: [
      {
        id: "demo-material-weathertech-underlayment",
        job_id: weatherTechJobId,
        name: "Tile underlayment rolls",
        quantity: 12,
        unit: "rolls",
        notes: "WeatherTech roofing material package.",
        created_at: now,
      },
      {
        id: "demo-material-ihc-paint",
        job_id: ihcJobId,
        name: "Dunn-Edwards exterior paint",
        quantity: 8,
        unit: "gallons",
        notes: "IHC painting material package.",
        created_at: now,
      },
    ],
    scheduleEvents: [
      {
        id: "demo-event-1",
        company_id: weatherTechCompanyId,
        customer_id: weatherTechCustomerId,
        lead_id: weatherTechLeadId,
        job_id: weatherTechJobId,
        title: "Demo Roof Inspection",
        event_type: "inspection",
        status: "scheduled",
        start_at: isoDateTime(1, 10),
        end_at: isoDateTime(1, 11),
        location: "1234 E Demo Roof Rd, Gilbert, AZ",
        notes: "Demo calendar item.",
        created_at: now,
        updated_at: now,
      },
      {
        id: "demo-event-2",
        company_id: ihcCompanyId,
        customer_id: ihcCustomerId,
        lead_id: ihcLeadId,
        job_id: ihcJobId,
        title: "Demo Paint Walkthrough",
        event_type: "job",
        status: "scheduled",
        start_at: isoDateTime(2, 9),
        end_at: isoDateTime(2, 10),
        location: "4567 S Demo Paint Ave, Chandler, AZ",
        notes: "Demo IHC calendar item.",
        created_at: now,
        updated_at: now,
      },
    ],
    jobPhotos: [],
    invoices: [
      {
        id: weatherTechInvoiceId,
        company_id: weatherTechCompanyId,
        customer_id: weatherTechCustomerId,
        job_id: weatherTechJobId,
        estimate_id: weatherTechEstimateId,
        invoice_number: "WT-DEMO-1001",
        title: "Demo Roof Deposit Invoice",
        status: "sent",
        issue_date: isoDate(0),
        due_date: isoDate(7),
        subtotal: 5000,
        tax_rate: 0,
        tax_total: 0,
        discount_total: 0,
        total: 5000,
        amount_paid: 0,
        balance_due: 5000,
        notes: "Demo invoice.",
        created_at: now,
        updated_at: now,
      },
    ],
    invoiceLineItems: [
      {
        id: "demo-invoice-line-1",
        invoice_id: weatherTechInvoiceId,
        description: "Project deposit",
        quantity: 1,
        unit_cost: 5000,
        taxable: false,
        sort_order: 1,
        total: 5000,
        created_at: now,
        updated_at: now,
      },
    ],
    materialOrders: [],
    materialOrderItems: [],
    employees: [
      {
        id: employeeId,
        company_id: weatherTechCompanyId,
        full_name: "Demo Crew Lead",
        role: "crew_lead",
        phone: "(480) 555-0133",
        email: "crew@example.com",
        is_active: true,
        created_at: now,
        updated_at: now,
      },
    ],
    jobAssignments: [
      {
        id: "demo-assignment-1",
        company_id: weatherTechCompanyId,
        employee_id: employeeId,
        job_id: weatherTechJobId,
        schedule_event_id: "demo-event-1",
        title: "Demo crew assignment",
        status: "assigned",
        assigned_date: isoDate(3),
        notes: "Demo assignment.",
        created_at: now,
        updated_at: now,
      },
    ],
    timeEntries: [],
    inspections: [],
    dailyLogs: [],
    changeOrders: [],
    signatures: [],
    documents: [],
    payments: [],
    notifications: [
      {
        id: "demo-notification-1",
        company_id: weatherTechCompanyId,
        customer_id: weatherTechCustomerId,
        employee_id: null,
        title: "Local demo mode active",
        message: "WeatherTech OS is using demo CRM data because live Supabase is not available.",
        channel: "in_app",
        status: "queued",
        remind_at: null,
        created_at: now,
        updated_at: now,
      },
    ],
    integrationConnections: [],
    integrationSyncLogs: [],
    calendarEventSyncs: [],
    emailMessages: [],
    smsMessages: [],
    routePlans: [],
    routePlanStops: [],
    companyMemberships: [],
    companyWorkflowSettings: [
      {
        company_id: weatherTechCompanyId,
        workflow_profile: "roofing",
        estimate_terms: "Demo roofing estimate terms.",
        invoice_terms: "Demo roofing invoice terms.",
        warranty_terms: "Demo roofing warranty terms.",
        production_checklist: ["Confirm materials", "Confirm crew", "Protect property", "Clean jobsite"],
        created_at: now,
        updated_at: now,
      },
      {
        company_id: ihcCompanyId,
        workflow_profile: "painting",
        estimate_terms: "Demo painting estimate terms.",
        invoice_terms: "Demo painting invoice terms.",
        warranty_terms: "Demo painting warranty terms.",
        production_checklist: ["Confirm colors", "Prep surfaces", "Apply finish coats", "Final walkthrough"],
        created_at: now,
        updated_at: now,
      },
    ],
  };
}
