import type { CrmSnapshot } from "./types";

const createdAt = "2026-06-29T08:00:00.000Z";
const updatedAt = "2026-06-29T15:30:00.000Z";

const weatherTechCompanyId = "demo-company-weathertech-roofing";
const ihcCompanyId = "demo-company-ihc-painting";
const roofingCustomerId = "demo-customer-desert-ridge";
const paintingCustomerId = "demo-customer-arcadia-refresh";
const roofingLeadId = "demo-lead-monsoon-roof";
const paintingLeadId = "demo-lead-cabinet-refresh";
const roofingEstimateId = "demo-estimate-roof-underlayment";
const paintingEstimateId = "demo-estimate-interior-paint";
const roofingJobId = "demo-job-roof-underlayment";
const paintingJobId = "demo-job-interior-paint";
const roofingInvoiceId = "demo-invoice-roof-deposit";
const roofingEmployeeId = "demo-employee-elena";
const paintingEmployeeId = "demo-employee-marco";
const googleCalendarConnectionId = "demo-integration-google-calendar";
const gmailConnectionId = "demo-integration-gmail";
const twilioConnectionId = "demo-integration-twilio";
const roofingScheduleEventId = "demo-event-roof-inspection";
const paintingScheduleEventId = "demo-event-paint-walkthrough";
const routePlanId = "demo-route-today";

export const demoCrmSnapshot = {
  companies: [
    {
      id: weatherTechCompanyId,
      name: "WeatherTech Roofing LLC",
      trade: "roofing",
      short_name: "WeatherTech",
      brand_color: "#0284c7",
      workflow_profile: "roofing",
      phone: "480-555-0110",
      email: "office@weathertechroofingaz.example",
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: ihcCompanyId,
      name: "IHC Painting",
      trade: "painting",
      short_name: "IHC",
      brand_color: "#7c3aed",
      workflow_profile: "painting",
      phone: "480-555-0198",
      email: "hello@ihcpainting.example",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  leads: [
    {
      id: roofingLeadId,
      company_id: weatherTechCompanyId,
      customer_id: null,
      contact_name: "Avery Martinez",
      phone: "480-555-0144",
      email: "avery.martinez@example.com",
      property_address: "2148 E Desert Ridge Dr",
      city: "Phoenix",
      state: "AZ",
      postal_code: "85050",
      latitude: 33.6844,
      longitude: -111.9732,
      google_place_id: null,
      address_verified_at: null,
      service_type: "roofing",
      source: "GoHighLevel / Website form",
      status: "qualified",
      priority: "urgent",
      estimated_value: 26800,
      next_follow_up: "2026-06-30T16:00:00.000Z",
      notes: "Monsoon leak near garage valley. Wants inspection and photo-backed estimate.",
      created_by: null,
      created_at: "2026-06-28T17:10:00.000Z",
      updated_at: updatedAt,
    },
    {
      id: paintingLeadId,
      company_id: ihcCompanyId,
      customer_id: null,
      contact_name: "Priya Shah",
      phone: "480-555-0155",
      email: "priya.shah@example.com",
      property_address: "4421 N 39th Pl",
      city: "Phoenix",
      state: "AZ",
      postal_code: "85018",
      latitude: 33.5001,
      longitude: -111.9969,
      google_place_id: null,
      address_verified_at: null,
      service_type: "painting",
      source: "Referral",
      status: "contacted",
      priority: "high",
      estimated_value: 9200,
      next_follow_up: "2026-07-01T18:30:00.000Z",
      notes: "Kitchen cabinet refinishing and interior accent wall. Needs color consult.",
      created_by: null,
      created_at: "2026-06-27T19:15:00.000Z",
      updated_at: updatedAt,
    },
  ],
  customers: [
    {
      id: roofingCustomerId,
      company_id: weatherTechCompanyId,
      display_name: "Morgan Residence",
      contact_name: "Morgan Lee",
      phone: "480-555-0101",
      email: "morgan.lee@example.com",
      property_address: "7331 E Via de la Escuela",
      city: "Scottsdale",
      state: "AZ",
      postal_code: "85258",
      customer_type: "homeowner",
      status: "active",
      notes: "Tile roof underlayment replacement. Prefers text updates.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: paintingCustomerId,
      company_id: ihcCompanyId,
      display_name: "Arcadia Refresh Project",
      contact_name: "Jamie Wilson",
      phone: "480-555-0127",
      email: "jamie.wilson@example.com",
      property_address: "3910 E Campbell Ave",
      city: "Phoenix",
      state: "AZ",
      postal_code: "85018",
      customer_type: "homeowner",
      status: "active",
      notes: "Interior repaint with Dunn-Edwards palette. Wants daily end-of-day updates.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  estimates: [
    {
      id: roofingEstimateId,
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      lead_id: null,
      title: "Tile roof lift-and-relay underlayment",
      status: "sent",
      service_type: "roofing",
      issue_date: "2026-06-26",
      expiration_date: "2026-07-10",
      subtotal: 23850,
      labor_total: 10400,
      material_total: 10150,
      tax_rate: 0,
      tax_total: 0,
      discount_type: "fixed",
      discount_value: 0,
      discount_total: 0,
      profit_margin_rate: 0.14,
      profit_margin_total: 3300,
      total: 23850,
      notes: "Includes tile removal, self-adhered underlayment, metal flashings, reset, and cleanup.",
      painting_area_type: null,
      paint_brand: "Dunn-Edwards",
      paint_product_line: null,
      paint_finish: null,
      color_selection_status: "not_started",
      paint_color_body: null,
      paint_color_trim: null,
      paint_color_accent: null,
      surface_prep_level: null,
      coats: 2,
      primer_required: false,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: paintingEstimateId,
      company_id: ihcCompanyId,
      customer_id: paintingCustomerId,
      lead_id: null,
      title: "Interior repaint and accent package",
      status: "approved",
      service_type: "painting",
      issue_date: "2026-06-24",
      expiration_date: "2026-07-08",
      subtotal: 7400,
      labor_total: 4800,
      material_total: 1450,
      tax_rate: 0.086,
      tax_total: 125,
      discount_type: "fixed",
      discount_value: 0,
      discount_total: 0,
      profit_margin_rate: 0.14,
      profit_margin_total: 1025,
      total: 7525,
      notes: "Includes wall repairs, two coats, trim touch-up, and color confirmation.",
      painting_area_type: "interior",
      paint_brand: "Dunn-Edwards",
      paint_product_line: "Spartawall",
      paint_finish: "eggshell",
      color_selection_status: "in_review",
      paint_color_body: "DEW380 Warm White",
      paint_color_trim: "DEW340 Whisper",
      paint_color_accent: "DEC756 Weathered Brown",
      surface_prep_level: "enhanced",
      coats: 2,
      primer_required: true,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  estimateLineItems: [
    {
      id: "demo-line-roof-labor",
      estimate_id: roofingEstimateId,
      category: "labor",
      name: "Tile lift, relay, and detail labor",
      description: "Crew labor for tile removal, staging, underlayment prep, relay, and site cleanup.",
      quantity: 1,
      unit: "project",
      unit_cost: 10400,
      markup_rate: 0,
      taxable: false,
      sort_order: 0,
      total: 10400,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-line-roof-material",
      estimate_id: roofingEstimateId,
      category: "material",
      name: "Underlayment, flashings, battens, and sealants",
      description: "Roofing material package staged for scheduled install.",
      quantity: 1,
      unit: "package",
      unit_cost: 10150,
      markup_rate: 0,
      taxable: true,
      sort_order: 1,
      total: 10150,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-line-paint-labor",
      estimate_id: paintingEstimateId,
      category: "labor",
      name: "Interior prep and painting labor",
      description: "Masking, drywall touchups, two coats, trim touch-up, and final walkthrough.",
      quantity: 1,
      unit: "project",
      unit_cost: 4800,
      markup_rate: 0,
      taxable: false,
      sort_order: 0,
      total: 4800,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-line-paint-material",
      estimate_id: paintingEstimateId,
      category: "material",
      name: "Dunn-Edwards paint and prep materials",
      description: "Primer, wall paint, trim paint, plastic, tape, and sundries.",
      quantity: 1,
      unit: "package",
      unit_cost: 1450,
      markup_rate: 0,
      taxable: true,
      sort_order: 1,
      total: 1450,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  scopeTemplates: [
    {
      id: "demo-template-roof-underlayment",
      company_id: weatherTechCompanyId,
      title: "Tile underlayment scope",
      category: "tile_underlayment",
      description: "Standard scope for tile roof lift-and-relay projects.",
      template_body: "Inspect deck, remove and stack tile, install underlayment, update flashings, relay tile, clean site, and document photos.",
      ai_prompt: "Draft a tile roof underlayment scope using inspection notes, photos, and material selections.",
      is_active: true,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-template-interior-paint",
      company_id: ihcCompanyId,
      title: "Interior painting scope",
      category: "interior_painting",
      description: "Standard scope for interior repaint jobs.",
      template_body: "Confirm colors, protect surfaces, prep walls, prime where needed, apply finish coats, complete punch list, and walk customer through final review.",
      ai_prompt: "Create a customer-ready interior painting scope from rooms, colors, prep level, and finish selections.",
      is_active: true,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  scopes: [
    {
      id: "demo-scope-roof-underlayment",
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      lead_id: null,
      estimate_id: roofingEstimateId,
      template_id: "demo-template-roof-underlayment",
      title: "Scope: Morgan tile roof underlayment",
      category: "tile_underlayment",
      status: "sent",
      scope_body: "Lift existing tile, inspect decking, replace compromised battens, install self-adhered underlayment, refresh metal flashings, relay tile, magnet sweep, and photo document completion.",
      notes: "Customer asked for driveway protection and daily progress texts.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-scope-paint-interior",
      company_id: ihcCompanyId,
      customer_id: paintingCustomerId,
      lead_id: null,
      estimate_id: paintingEstimateId,
      template_id: "demo-template-interior-paint",
      title: "Scope: Arcadia interior refresh",
      category: "interior_painting",
      status: "approved",
      scope_body: "Protect floors and fixtures, repair nail pops and minor drywall defects, prime patched areas, apply two coats, complete accent wall, touch up trim, label leftover paint, and complete final walkthrough.",
      notes: "Color approval needed before material pull.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  jobs: [
    {
      id: roofingJobId,
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      lead_id: null,
      estimate_id: roofingEstimateId,
      scope_id: "demo-scope-roof-underlayment",
      title: "Morgan tile roof underlayment",
      service_type: "roofing",
      status: "scheduled",
      start_date: "2026-07-08",
      end_date: "2026-07-11",
      crew_name: "Roof Crew A",
      project_manager: "Elena Cruz",
      property_address: "7331 E Via de la Escuela, Scottsdale, AZ 85258",
      latitude: 33.5261,
      longitude: -111.9247,
      google_place_id: null,
      address_verified_at: null,
      notes: "Materials to be staged July 7. Confirm tile stack area.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: paintingJobId,
      company_id: ihcCompanyId,
      customer_id: paintingCustomerId,
      lead_id: null,
      estimate_id: paintingEstimateId,
      scope_id: "demo-scope-paint-interior",
      title: "Arcadia interior repaint",
      service_type: "painting",
      status: "in_progress",
      start_date: "2026-06-29",
      end_date: "2026-07-02",
      crew_name: "IHC Interior Crew",
      project_manager: "Marco Ruiz",
      property_address: "3910 E Campbell Ave, Phoenix, AZ 85018",
      latitude: 33.5019,
      longitude: -111.9965,
      google_place_id: null,
      address_verified_at: null,
      notes: "Customer works from home; quiet hours after 3 PM.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  scheduleEvents: [
    {
      id: roofingScheduleEventId,
      company_id: weatherTechCompanyId,
      customer_id: null,
      lead_id: roofingLeadId,
      job_id: null,
      title: "Emergency leak inspection - Avery Martinez",
      event_type: "inspection",
      status: "scheduled",
      start_at: "2026-06-30T16:00:00.000Z",
      end_at: "2026-06-30T17:00:00.000Z",
      location: "2148 E Desert Ridge Dr, Phoenix, AZ 85050",
      notes: "Capture attic, valley, and roof photos. Check monsoon risk.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: paintingScheduleEventId,
      company_id: ihcCompanyId,
      customer_id: paintingCustomerId,
      lead_id: null,
      job_id: paintingJobId,
      title: "Paint color walkthrough",
      event_type: "job",
      status: "scheduled",
      start_at: "2026-06-30T15:30:00.000Z",
      end_at: "2026-06-30T16:15:00.000Z",
      location: "3910 E Campbell Ave, Phoenix, AZ 85018",
      notes: "Confirm accent wall before final paint order.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  jobPhotos: [
    {
      id: "demo-photo-roof-before",
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      job_id: roofingJobId,
      estimate_id: roofingEstimateId,
      caption: "Pre-production roof tile and valley detail photo placeholder.",
      file_path: "demo/roof-before.jpg",
      file_url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e",
      taken_at: "2026-06-26T17:45:00.000Z",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  invoices: [
    {
      id: roofingInvoiceId,
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      job_id: roofingJobId,
      estimate_id: roofingEstimateId,
      invoice_number: "WT-2026-1042",
      title: "Deposit - tile roof underlayment",
      status: "sent",
      issue_date: "2026-06-27",
      due_date: "2026-07-03",
      subtotal: 8400,
      tax_rate: 0,
      tax_total: 0,
      discount_total: 0,
      total: 8400,
      amount_paid: 4000,
      balance_due: 4400,
      notes: "Deposit invoice before material staging.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  invoiceLineItems: [
    {
      id: "demo-invoice-line-roof-deposit",
      invoice_id: roofingInvoiceId,
      description: "Production deposit for tile roof underlayment project",
      quantity: 1,
      unit_cost: 8400,
      taxable: false,
      sort_order: 0,
      total: 8400,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  materialOrders: [
    {
      id: "demo-material-roof-order",
      company_id: weatherTechCompanyId,
      job_id: roofingJobId,
      supplier_name: "ABC Supply",
      status: "ordered",
      requested_date: "2026-06-28",
      expected_delivery_date: "2026-07-07",
      delivery_address: "7331 E Via de la Escuela, Scottsdale, AZ 85258",
      total: 6150,
      notes: "Confirm driveway drop zone and tile stack protection.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  materialOrderItems: [
    {
      id: "demo-material-item-underlayment",
      material_order_id: "demo-material-roof-order",
      name: "Self-adhered underlayment rolls",
      quantity: 32,
      unit: "roll",
      unit_cost: 145,
      sort_order: 0,
      total: 4640,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-material-item-flashing",
      material_order_id: "demo-material-roof-order",
      name: "Valley metal, drip edge, and sealants",
      quantity: 1,
      unit: "package",
      unit_cost: 1510,
      sort_order: 1,
      total: 1510,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  employees: [
    {
      id: roofingEmployeeId,
      company_id: weatherTechCompanyId,
      full_name: "Elena Cruz",
      role: "project_manager",
      phone: "480-555-0161",
      email: "elena@weathertechroofingaz.example",
      is_active: true,
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: paintingEmployeeId,
      company_id: ihcCompanyId,
      full_name: "Marco Ruiz",
      role: "crew_lead",
      phone: "480-555-0172",
      email: "marco@ihcpainting.example",
      is_active: true,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  jobAssignments: [
    {
      id: "demo-assignment-roof-pm",
      company_id: weatherTechCompanyId,
      employee_id: roofingEmployeeId,
      job_id: roofingJobId,
      schedule_event_id: null,
      title: "Project manager",
      status: "assigned",
      assigned_date: "2026-07-08",
      notes: "Run pre-start call and daily photo updates.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: "demo-assignment-paint-crew",
      company_id: ihcCompanyId,
      employee_id: paintingEmployeeId,
      job_id: paintingJobId,
      schedule_event_id: paintingScheduleEventId,
      title: "Crew lead",
      status: "accepted",
      assigned_date: "2026-06-29",
      notes: "Confirm accent wall and color signoff.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  timeEntries: [
    {
      id: "demo-time-paint-day-one",
      company_id: ihcCompanyId,
      employee_id: paintingEmployeeId,
      job_id: paintingJobId,
      clock_in_at: "2026-06-29T14:00:00.000Z",
      clock_out_at: null,
      break_minutes: 30,
      status: "clocked_in",
      notes: "Prep, masking, and patch work underway.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  inspections: [
    {
      id: "demo-inspection-roof",
      company_id: weatherTechCompanyId,
      employee_id: roofingEmployeeId,
      job_id: roofingJobId,
      title: "Pre-production roof inspection",
      status: "pending",
      checklist: "Verify tile count, underlayment area, access, driveway protection, and attic leak path.",
      completed_at: null,
      notes: "Inspection scheduled before material staging.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  dailyLogs: [
    {
      id: "demo-daily-log-paint",
      company_id: ihcCompanyId,
      employee_id: paintingEmployeeId,
      job_id: paintingJobId,
      log_date: "2026-06-29",
      weather_summary: "Clear, interior work unaffected.",
      work_completed: "Protected floors, masked fixtures, patched nail holes, and started primer in main hallway.",
      blockers: "Waiting on final accent color approval.",
      tomorrow_plan: "Finish primer, begin first wall coat, confirm accent wall before lunch.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  changeOrders: [
    {
      id: "demo-change-order-paint-accent",
      company_id: ihcCompanyId,
      customer_id: paintingCustomerId,
      job_id: paintingJobId,
      estimate_id: paintingEstimateId,
      title: "Add bedroom accent wall",
      status: "draft",
      reason: "Customer requested one additional accent wall after walkthrough.",
      amount: 650,
      tax_rate: 0.086,
      tax_total: 56,
      total: 706,
      requested_date: "2026-06-29",
      approved_at: null,
      notes: "Needs approval before material pull.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  signatures: [
    {
      id: "demo-signature-roof-scope",
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      employee_id: null,
      document_id: "demo-document-roof-contract",
      change_order_id: null,
      signer_name: "Morgan Lee",
      signer_email: "morgan.lee@example.com",
      status: "pending",
      signature_data: null,
      signed_at: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  documents: [
    {
      id: "demo-document-roof-contract",
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      job_id: roofingJobId,
      estimate_id: roofingEstimateId,
      invoice_id: roofingInvoiceId,
      change_order_id: null,
      title: "Roof underlayment contract packet",
      category: "contract",
      status: "sent",
      template_key: "roofing_contract",
      file_url: null,
      body: "Demo contract packet generated from estimate, scope, payment schedule, and production terms.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  payments: [
    {
      id: "demo-payment-roof-deposit",
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      invoice_id: roofingInvoiceId,
      amount: 4000,
      method: "card",
      status: "posted",
      paid_at: "2026-06-28T18:20:00.000Z",
      reference: "DEMO-PAY-1042",
      notes: "Deposit posted through demo payment record.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  notifications: [
    {
      id: "demo-notification-follow-up",
      company_id: weatherTechCompanyId,
      customer_id: null,
      employee_id: roofingEmployeeId,
      title: "Urgent inspection follow-up",
      message: "Avery Martinez has an urgent monsoon leak inspection tomorrow at 9 AM Phoenix time.",
      channel: "in_app",
      status: "queued",
      remind_at: "2026-06-30T15:30:00.000Z",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  integrationConnections: [
    {
      id: googleCalendarConnectionId,
      company_id: weatherTechCompanyId,
      provider: "google_calendar",
      status: "connected",
      account_email: "calendar@weathertechroofingaz.example",
      display_name: "WeatherTech Production Calendar",
      external_account_id: "demo-google-calendar-account",
      default_calendar_id: "primary",
      scopes: ["https://www.googleapis.com/auth/calendar.events"],
      sync_direction: "two_way",
      credential_reference: "demo-google-calendar-secret",
      webhook_channel_id: null,
      webhook_resource_id: null,
      sync_token: null,
      last_sync_at: "2026-06-29T15:15:00.000Z",
      last_error: null,
      settings: { demo: true },
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: gmailConnectionId,
      company_id: weatherTechCompanyId,
      provider: "gmail",
      status: "needs_reauth",
      account_email: "office@weathertechroofingaz.example",
      display_name: "Office Gmail",
      external_account_id: "demo-gmail-account",
      default_calendar_id: null,
      scopes: ["https://www.googleapis.com/auth/gmail.send"],
      sync_direction: "weathertech_to_provider",
      credential_reference: null,
      webhook_channel_id: null,
      webhook_resource_id: null,
      sync_token: null,
      last_sync_at: null,
      last_error: "Demo: reconnect Gmail before sending live messages.",
      settings: { demo: true },
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      id: twilioConnectionId,
      company_id: weatherTechCompanyId,
      provider: "twilio_sms",
      status: "paused",
      account_email: null,
      display_name: "Twilio SMS",
      external_account_id: "demo-twilio-account",
      default_calendar_id: null,
      scopes: [],
      sync_direction: "weathertech_to_provider",
      credential_reference: null,
      webhook_channel_id: null,
      webhook_resource_id: null,
      sync_token: null,
      last_sync_at: null,
      last_error: null,
      settings: { demo: true, fromPhone: "+14805550123" },
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  calendarEventSyncs: [
    {
      id: "demo-calendar-sync-roof-inspection",
      company_id: weatherTechCompanyId,
      schedule_event_id: roofingScheduleEventId,
      integration_connection_id: googleCalendarConnectionId,
      provider: "google_calendar",
      google_calendar_id: "primary",
      google_event_id: "demo-google-event-roof-inspection",
      sync_status: "synced",
      sync_direction: "two_way",
      last_synced_at: "2026-06-29T15:15:00.000Z",
      external_updated_at: "2026-06-29T15:15:00.000Z",
      last_error: null,
      last_payload_hash: "demo-roof-inspection-hash",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  emailMessages: [
    {
      id: "demo-email-estimate-follow-up",
      company_id: weatherTechCompanyId,
      customer_id: roofingCustomerId,
      estimate_id: roofingEstimateId,
      invoice_id: null,
      document_id: "demo-document-roof-contract",
      integration_connection_id: gmailConnectionId,
      provider: "gmail",
      category: "estimate",
      status: "draft",
      to_email: "morgan.lee@example.com",
      cc_email: null,
      subject: "WeatherTech Roofing - production schedule and next steps",
      body: "Hi Morgan, here are the next steps for your tile roof underlayment project, including schedule, deposit, and material staging details.",
      gmail_message_id: null,
      queued_at: null,
      sent_at: null,
      last_error: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  smsMessages: [
    {
      id: "demo-sms-inspection-reminder",
      company_id: weatherTechCompanyId,
      customer_id: null,
      lead_id: roofingLeadId,
      job_id: null,
      schedule_event_id: roofingScheduleEventId,
      invoice_id: null,
      integration_connection_id: twilioConnectionId,
      provider: "twilio_sms",
      category: "appointment_reminder",
      status: "draft",
      to_phone: "480-555-0144",
      from_phone: "+14805550123",
      body: "Hi Avery, WeatherTech Roofing has your roof inspection scheduled for tomorrow morning. Reply with any gate or access notes. Reply STOP to opt out.",
      twilio_message_sid: null,
      queued_at: null,
      sent_at: null,
      last_error: null,
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  routePlans: [
    {
      id: routePlanId,
      company_id: weatherTechCompanyId,
      name: "Tomorrow inspection route",
      route_date: "2026-06-30",
      status: "optimized",
      origin_address: "WeatherTech Roofing Office, Phoenix, AZ",
      destination_address: "WeatherTech Roofing Office, Phoenix, AZ",
      travel_mode: "driving",
      avoid_tolls: true,
      avoid_highways: false,
      total_distance_meters: 38400,
      total_duration_seconds: 3600,
      estimated_fuel_cost: 18.5,
      google_route_token: null,
      encoded_polyline: null,
      provider_payload: { demo: true },
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  routePlanStops: [
    {
      id: "demo-route-stop-roof-inspection",
      route_plan_id: routePlanId,
      company_id: weatherTechCompanyId,
      stop_type: "lead",
      lead_id: roofingLeadId,
      job_id: null,
      schedule_event_id: roofingScheduleEventId,
      sort_order: 0,
      title: "Avery Martinez emergency leak inspection",
      address: "2148 E Desert Ridge Dr, Phoenix, AZ 85050",
      latitude: 33.6844,
      longitude: -111.9732,
      google_place_id: null,
      estimated_arrival_at: "2026-06-30T16:00:00.000Z",
      estimated_departure_at: "2026-06-30T17:00:00.000Z",
      distance_from_previous_meters: 19200,
      duration_from_previous_seconds: 1800,
      notes: "Capture leak, roof, attic, and valley photos.",
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
  companyMemberships: [],
  companyWorkflowSettings: [
    {
      company_id: weatherTechCompanyId,
      workflow_profile: "roofing",
      estimate_terms: "Demo roofing terms: schedule is reserved after approval and deposit.",
      invoice_terms: "Deposit due before material staging. Balance due at substantial completion.",
      warranty_terms: "Demo warranty terms to be replaced with WeatherTech approved language.",
      production_checklist: [
        "Confirm access and driveway protection",
        "Capture before photos",
        "Verify material staging",
        "Send daily production update",
        "Complete final magnet sweep and photo packet"
      ],
      created_at: createdAt,
      updated_at: updatedAt,
    },
    {
      company_id: ihcCompanyId,
      workflow_profile: "painting",
      estimate_terms: "Demo painting terms: color approval required before production start.",
      invoice_terms: "Progress billing follows approved scope and change orders.",
      warranty_terms: "Demo painting warranty terms to be replaced with IHC approved language.",
      production_checklist: [
        "Confirm paint colors and finishes",
        "Protect floors, furniture, and fixtures",
        "Document surface prep",
        "Complete punch list with customer",
        "Label leftover paint"
      ],
      created_at: createdAt,
      updated_at: updatedAt,
    },
  ],
} satisfies CrmSnapshot;

export function createDemoCrmSnapshot(): CrmSnapshot {
  return JSON.parse(JSON.stringify(demoCrmSnapshot)) as CrmSnapshot;
}
