import type { CompanyRecord, CrmSnapshot } from "./types";

const now = new Date("2026-06-26T12:00:00.000Z").toISOString();

export const demoCompanies: CompanyRecord[] = [
  {
    id: "company-weathertech",
    name: "WeatherTech Roofing LLC",
    trade: "roofing",
    phone: null,
    email: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "company-ihc",
    name: "IHC Painting",
    trade: "painting",
    phone: null,
    email: null,
    created_at: now,
    updated_at: now,
  },
];

export const demoCrmSnapshot: CrmSnapshot = {
  companies: demoCompanies,
  customers: [
    {
      id: "customer-maple",
      company_id: "company-ihc",
      display_name: "Maple Ave Residence",
      contact_name: "Jordan Lee",
      phone: "(480) 555-0142",
      email: "jordan@example.com",
      property_address: "428 Maple Ave",
      city: "Mesa",
      state: "AZ",
      postal_code: "85201",
      customer_type: "homeowner",
      status: "active",
      notes: "Exterior painting customer.",
      created_at: now,
      updated_at: now,
    },
    {
      id: "customer-parkside",
      company_id: "company-weathertech",
      display_name: "Parkside Townhouse",
      contact_name: "Avery Morgan",
      phone: "(602) 555-0198",
      email: "avery@example.com",
      property_address: "890 Parkside Dr",
      city: "Phoenix",
      state: "AZ",
      postal_code: "85016",
      customer_type: "hoa",
      status: "prospect",
      notes: "Needs roof inspection before estimate.",
      created_at: now,
      updated_at: now,
    },
  ],
  leads: [
    {
      id: "lead-east-ridge",
      company_id: "company-weathertech",
      customer_id: null,
      contact_name: "East Ridge Home",
      phone: "(480) 555-0108",
      email: "east@example.com",
      property_address: "1128 East Ridge Ln",
      city: "Scottsdale",
      state: "AZ",
      postal_code: "85251",
      service_type: "roofing",
      source: "Website",
      status: "new",
      priority: "high",
      estimated_value: 7800,
      next_follow_up: "2026-06-29",
      notes: "Roof replacement inquiry.",
      created_by: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-maple",
      company_id: "company-ihc",
      customer_id: "customer-maple",
      contact_name: "Maple Ave Residence",
      phone: "(480) 555-0142",
      email: "jordan@example.com",
      property_address: "428 Maple Ave",
      city: "Mesa",
      state: "AZ",
      postal_code: "85201",
      service_type: "painting",
      source: "Referral",
      status: "contacted",
      priority: "normal",
      estimated_value: 4200,
      next_follow_up: "2026-06-30",
      notes: "Exterior repaint with trim.",
      created_by: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-parkside",
      company_id: "company-weathertech",
      customer_id: "customer-parkside",
      contact_name: "Parkside Townhouse",
      phone: "(602) 555-0198",
      email: "avery@example.com",
      property_address: "890 Parkside Dr",
      city: "Phoenix",
      state: "AZ",
      postal_code: "85016",
      service_type: "roofing",
      source: "Google Ad",
      status: "qualified",
      priority: "urgent",
      estimated_value: 12500,
      next_follow_up: "2026-06-28",
      notes: "HOA roof leak after monsoon storm.",
      created_by: null,
      created_at: now,
      updated_at: now,
    },
  ],
};
